# vim: ft=conf
# Linux overrides — linked to ~/.config/ghostty/os.conf by links/linux.links.

font-size = 12
adjust-cell-height = 7%

window-decoration = false
unfocused-split-opacity = 0.7

gtk-titlebar = false
gtk-single-instance = true
